### ISSUE TITLE
Kernel version 6.5.9 mainline

### ISSUE THREAD

**Issue by arimal199** [alf45tar/ix4-300d#1]
I want to install the newest kernel.
I understand I'll have to compile it myself.
Please provide the tutorial to do so, with the option to compile for armhf on amd64

**Comment by alf45tar** [comment]
I used the standard Debian procedure https://wiki.debian.org/HowToCrossBuildAnOfficialDebianKernelPackage
If I remember well I used
```
ARCH=armmp-lpae
```
and deleted FEATURESET and FLAVOUR into the script.

Check here https://forum.doozan.com/read.php?2,32146 for 6.5.7 already compiled.

**Comment by arimal199** [comment]
Thanks!
