### ISSUE TITLE
Not Detect Hard Disk

### ISSUE THREAD

**Issue by amroth3003** [alf45tar/ix4-300d#2]
Hello, I am following the steps to install debian on ix4-300d but it is not detecting the disks, I have tried one by one and before trying to install debian, the nas worked with the Lenovo software

![image](https://github.com/alf45tar/ix4-300d/assets/46945805/dd3a03e4-ceaa-4e13-84d9-0fd5b7d57b6c)

**Comment by amroth3003** [comment]
Fixed, the problem occurs with the image uImage_di_ix4_300d_bookworm, install image uImage_di_ix4_300d_bullseye works for me Thanks

**Comment by alf45tar** [comment]
Installer is outdated and components/modules cannot be loaded.
Upgraded the installer the latest version as of today.
