### ISSUE TITLE
Modification for (ex Iomega) ix4-200d NAS

### ISSUE THREAD

**Issue by mundodisco-argentina** [alf45tar/ix4-300d#3]
Dear alf45tar,

do you think you could help me installing Debian on a ix4-200d NAS (you made it on the ix4-300d,,,similar, but not identical). I have now the NAS with OpenWRT, but this solution is very limited as it installs on the internal flash memory (32MB), and it does not support all the SATA controllers (it has problems detecting drives on ports 1 & 2). Debian, installed on an external USB pendrive, would have wider software capabilities and surely it would detect all drives...

I am willing to help with all the testing and providing logs and information, of course!

Kind regards,
Gabriel (from Buenos Aires, Argentina)
gabrielcallegari@gmail.com

PS: sorry to use this space to communicate with you!

**Comment by alf45tar** [comment]
Hi Gabriel, I suggest to start here https://forum.doozan.com/read.php?2,12096

**Comment by GGontijo** [comment]
Hi @mundodisco-argentina,

I saw that you worked on installing OpenWRT on the ix4-200d NAS, and I’d love to exchange some ideas about that. Additionally, I’m also interested in discussing the possibility of installing Debian on the device, if you’ve made any progress on that front.

Please feel free to reach out to me via email—my contact info is on my profile, as I couldn't find yours.

Looking forward to connecting!

Best regards.
