### ISSUE TITLE
Permanent boot debian

### ISSUE THREAD

**Issue by epasinetti** [alf45tar/ix4-300d#5]
After installing Debian the device still boot with old OS... how can I solve ? if I boot with this command from serial console 

ide reset; ext2load ide 2:1 0x0040000 uImage; ext2load ide 2:1 0x2000000 uInitrd; setenv bootargs $console $mtdparts root=LABEL=rootfs rw rootdelay=5; bootm 0x40000 0x2000000

Debian boot with no issue ... when I turn off the NAS and reboot , strart again from old OS.

**Comment by alf45tar** [comment]
Here the commands to permanent boot debian.
```
setenv bootdebian 'ide reset; ext2load ide 2:1 0x0040000 uImage; ext2load ide 2:1 0x2000000 uInitrd; setenv bootargs $console $mtdparts root=LABEL=rootfs rw rootdelay=5; bootm 0x40000 0x2000000;'
setenv bootcmd 'run bootdebian; reset;'
saveenv
reset
```

**Comment by epasinetti** [comment]
Great ! it work !
