### ISSUE TITLE
Ttl usb

### ISSUE THREAD

**Issue by marcorebelde89** [alf45tar/ix4-300d#6]
Hi, could you kindly suggest me a ttl usb converter to buy? Thanks

**Comment by alf45tar** [comment]
I am using an Arduino Uno with RESET shorted to GND.

https://www.instructables.com/How-to-Use-Arduino-As-USB-to-TTL-Serial-Converter-/

**Comment by marcorebelde89** [comment]
Ok thanks, and what about with this ones?
https://www.amazon.it/s?k=USB-to-TTL+adapter&__mk_it_IT=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=2D6DDXEC5AUYQ&sprefix=usb-to-ttl+adapter%2Caps%2C117&ref=nb_sb_noss_2
I would only use it on this occasion, so I wouldn't want to spend a lot

**Comment by alf45tar** [comment]
I agree with you. Do not sped too much. The cheaper one should work.

**Comment by 5p0ng3b0b** [comment]
> Hi, could you kindly suggest me a ttl usb converter to buy? Thanks

You could get a NodeMcu and set it up to access wirelessly with firmware from here https://github.com/jeelabs/esp-link
