### ISSUE TITLE
disable bright LCD?

### ISSUE THREAD

**Issue by nedson** [alf45tar/ix4-300d#7]
Hello!

Any idea how to completely disable the LCD? It is BRIGHT! I'd like to completely turn it off...with the ability to turn on if needed...maybe create a cronjob to turn on during the daylight hours and turn off at night.

I tried:

echo -1 > /sys/class/i2c-adapter/i2c-0/0-002e/hwmon/hwmon1/pwm3

any ideas? Thanks for compiling all of the info about this little NAS?

**Comment by alf45tar** [comment]
Not sure if you can power off it. You can only redure the backlight to zero

`echo 0 > /sys/class/i2c-adapter/i2c-0/0-002e/hwmon/hwmon1/pwm3`

**Comment by nedson** [comment]
Got it. Well, I guess I'll break out the foil and tape.

**Comment by 5p0ng3b0b** [comment]
My backlight died a long time ago lol
